### ISSUE TITLE
Publish the private JSDoc analysis API

### ISSUE THREAD

**Issue by atanasster** [jaydenseric/jsdoc-md#23]
Great project

What do you think about extracting jsdocCommentToMember into its own api? I would like to re-use that part of your library, without the markdown features? 

Thanks

**Comment by jaydenseric** [comment]
> Great project

Thanks :)

> What do you think about extracting jsdocCommentToMember into its own api? I would like to re-use that part of your library, without the markdown features?

To consider the best way to do this, it helps to understand the exact use case you have for the API; what do you intend to do with it?

Right now, `jsdocCommentToMember` gathers information from a subset of all the JSDoc tags that can be seen in the wild:

https://github.com/jaydenseric/jsdoc-md#tag-subset

If the private JSDoc analysis API was to be extracted and published in a standalone package, this subset might seem a bit arbitrary because it's exactly what's needed for `jsdoc-md`. Maybe that's fine and we could expand it over time as there is interest.

I always saw a need for a package like this, but wanted to figure out an elegant system in `jsdoc-md` first as it's easier to churn internals in one package than juggle releases between two packages. I think it's finally at a pretty nice point, having solved the last big problems relatively recently:

- Code file locations for values, for showing users where in the code their JSDoc errors are.
- Support synonyms for the subset of supported JSDoc tags.
- Support higher-level tags like `@callback` and `@typedef` that are necessary for TypeScript users. TypeScript doesn't understand `@kind typedef` in combination with `@name foo`.

**Comment by atanasster** [comment]
Thanks for the thorough reply.

my use case is to extract prop types from jsdoc on javascript/typescript files. The prop types are then used to auto generate documentation and tests.

so i am not really interested in source location, and maybe even most of the lesser known jsdoc. If you would like to extract the jsdoc analysis code, i would like to contribute to it. In the meantime, here is an isolated copy of your code i started and it kinda shows my use case as well (very early version of the package itself) https://github.com/ccontrols/component-controls/tree/api-documentation/misc/jsdoc-extract/src/jsdoc-md

**Comment by jaydenseric** [comment]
Closing because I'm phasing out use of this `jsdoc-md` package in my projects as I move to TypeScript JSDoc, and at this time I don't plan to seperate out and publish parts of the implementation.

The future of documentation is online web apps that take a JavaScript module URL, parse it looking at the TypeScript flavour of JSDoc, and dynamically present rich and even interactive documentation. Perhaps the best example of a tool like this is the Deno doc service:

https://doc.deno.land

Deno created a `deno doc` CLI that has a `--json` flag that's powered by a Rust crate:

- https://deno.land/manual/tools/documentation_generator
- https://github.com/denoland/deno_doc

These might be useful tools for people looking to analyse JSDoc in a CLI.

It's all very much a work in progress, but the future is promising.
