### ISSUE TITLE
Support JSDoc inline links

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/jsdoc-md#5]
See [the current caveat](https://github.com/jaydenseric/jsdoc-md#inline-tags).

This syntax might be the best to support:

```
See also [the `FooType` class]{@link FooType}.
```

**Comment by pur3miish** [comment]
Ok what about making a change to [mdToMdAst](https://github.com/jaydenseric/jsdoc-md/blob/master/lib/mdToMdAst.js) so that it can scrape the @link tags from the descriptions and return the MD AST.

We could potentially use something like [unist-util-filter](https://github.com/syntax-tree/unist-util-filter) ?

**Comment by jaydenseric** [comment]
I think we will need to add a second outlined members array argument to `mdToMdAst`, so we can determine the linked member (and slugger link) like here: https://github.com/jaydenseric/jsdoc-md/blob/v1.0.0/lib/typeJsdocAstToMdAst.js#L123
